"""First commit

Revision ID: 161b5ce3d361
Revises: bd995ccb88cf
Create Date: 2023-03-22 14:44:38.408586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161b5ce3d361'
down_revision = 'bd995ccb88cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ss', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ss')
    # ### end Alembic commands ###
