"""remove

Revision ID: ae0e7c60e9fa
Revises: 8fd83b823eb5
Create Date: 2023-03-22 15:03:24.686565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0e7c60e9fa'
down_revision = '8fd83b823eb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ss')
    op.drop_column('users', 'se')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('se', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ss', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
